### PR TITLE
Allow the use of I18n as we as i18n as the internationalisation array.

### PR DESCRIPTION
**Pull request by stevejhiggs**
If we request accept-language as just * and there is no primary language in the doc then just use the first language we find

### CODE REVIEW

**Comment by andyroyle** [comment]
travis is seemingly borked so i pulled the branch, got one test failure: 

```
1) i18n tests if we ask for * without a primary language then just use whatever comes first:

      AssertionError: expected true to be false
      + expected - actual

      +false
      -true

      at Assertion.prop.(anonymous function) (/Users/aroyle/Documents/repos/i18n-transform/node_modules/should/lib/should.js:61:14)
      at Context.<anonymous> (/Users/aroyle/Documents/repos/i18n-transform/tests/tests.js:527:34)
      at callFn (/Users/aroyle/Documents/repos/i18n-transform/node_modules/grunt-mocha-test/node_modules/mocha/lib/runnable.js:223:21)
      at Test.Runnable.run (/Users/aroyle/Documents/repos/i18n-transform/node_modules/grunt-mocha-test/node_modules/mocha/lib/runnable.js:216:7)
      at Runner.runTest (/Users/aroyle/Documents/repos/i18n-transform/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:374:10)
      at /Users/aroyle/Documents/repos/i18n-transform/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/aroyle/Documents/repos/i18n-transform/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:299:14)
      at /Users/aroyle/Documents/repos/i18n-transform/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/aroyle/Documents/repos/i18n-transform/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:247:23)
      at Object._onImmediate (/Users/aroyle/Documents/repos/i18n-transform/node_modules/grunt-mocha-test/node_modules/mocha/lib/runner.js:276:5)
```

**Comment by stevejhiggs** [comment]
In my mind I thought I fixed that. I think I got distracted by lunch

**Comment by andyroyle** [comment]
ah lunch, the eternal distraction

**Comment by andyroyle** [comment]
you should have perms to publish the updated package

**Pull request merged**
